// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("exports dojo/_base/lang dojo/_base/array dojo/_base/html dojo/has dojo/Deferred jimu/utils esri/lang esri/tasks/QueryTask esri/tasks/query".split(" "),function(h,v,q,A,w,u,t,D,E,F){function B(c){var a=v.clone(c.attributes);(c=c.geometry)&&"point"===c.type&&("x"in a?a._x=c.x:a.x=c.x,"y"in a?a._y=c.y:a.y=c.y);return a}h.exportCSV=function(c,a,b,d,f){return h._createCSVStr(a,b,d,f).then(function(e){return h._download(c+".csv",e)})};h.exportCalculatedResultsCSV=function(c,a){var b="",d=0;q.forEach(a,
function(f){b+=f.name+" ("+f.type+")\r\n";h._createCSVStr([],[],f.appendColumns,f.appendDatas).then(function(e){b+=e;d++;if(d===a.length)return h._download(c+".csv",b);b+="\r\n\r\n"})})};h.exportCSVFromFeatureLayer=function(c,a,b){b=b||{};return h._getExportData(a,{datas:b.datas,fromClient:b.fromClient,withGeometry:b.withGeometry,outFields:b.outFields,filterExpression:b.filterExpression}).then(function(d){return h._formattedData(a,d,{formatNumber:b.formatNumber,formatDate:b.formatDate,formatCodedValue:b.formatCodedValue,
popupInfo:b.popupInfo,appendColumns:b.appendColumns,appendDatas:b.appendDatas}).then(function(f){return h.exportCSV(c,f.datas,f.columns,f.appendColumns,f.appendDatas)})})};h.exportCSVByAttributes=function(c,a,b,d){d=v.mixin({},d);d.datas=b;return h.exportCSVFromFeatureLayer(c,a,d)};h.exportCSVByGraphics=function(c,a,b,d){b=q.map(b,function(f){return f.attributes});return h.exportCSVByAttributes(c,a,b,d)};h._createCSVStr=function(c,a,b,d){var f=new u,e="",g=0,k=0,l="",n="";try{if(a&&0<a.length){q.forEach(a,
function(m){e=e+l+m;l=","});e+="\r\n";g=c.length;k=a.length;for(var r=0;r<g;r++){l="";for(var p=0;p<k;p++)(n=c[r][a[p]])||"number"===typeof n||(n=""),n&&/[",\r\n]/g.test(n)&&(n='"'+n.replace(/(")/g,'""')+'"'),e=e+l+n,l=",";e+="\r\n"}}"undefined"!==typeof b&&"undefined"!==typeof d&&0<b.length&&0<d.length&&(l="",q.forEach(b,function(m){e=e+l+m;l=","}),l="",e+="\r\n",q.forEach(d,function(m){Array.isArray(m)?(q.forEach(m,function(x){e=e+l+x;l=","}),l="",e+="\r\n"):(e=e+l+m,l=",")}));f.resolve(e)}catch(m){console.error(m),
f.resolve("")}return f};h._isIE11=function(){return 11===t.has("ie")};h._isEdge=function(){return t.has("edge")};h._getDownloadUrl=function(c){return window.Blob&&window.URL&&window.URL.createObjectURL?(c=new Blob(["\ufeff"+c],{type:"text/csv"}),URL.createObjectURL(c)):"data:attachment/csv;charset\x3dutf-8,\ufeff"+encodeURIComponent(c)};h._download=function(c,a){var b=new u;try{if(w("ie")&&10>w("ie")){var d=window.top.open("about:blank","_blank");d.document.write("sep\x3d,\r\n"+a);d.document.close();
d.document.execCommand("SaveAs",!0,c);d.close()}else if(10===w("ie")||h._isIE11()||h._isEdge()){var f=new Blob(["\ufeff"+a],{type:"text/csv"});navigator.msSaveBlob(f,c)}else{var e=A.create("a",{href:h._getDownloadUrl(a),target:"_blank",download:c},document.body);if(w("safari")){var g=document.createEvent("MouseEvents");g.initEvent("click",!0,!0);e.dispatchEvent(g)}else e.click();A.destroy(e)}b.resolve()}catch(k){b.reject(k)}return b};h._getExportData=function(c,a){var b=new u,d=null,f=a.datas,e=a.withGeometry;
d=a.outFields;d&&d.length||(d=c.fields);d=v.clone(d);if(e&&!(f&&0<f.length)){var g="";g=-1!==d.indexOf("x")?"_x":"x";d.push({name:g,alias:g,format:{digitSeparator:!1,places:6},show:!0,type:"esriFieldTypeDouble"});g=-1!==d.indexOf("y")?"_y":"y";d.push({name:g,alias:g,format:{digitSeparator:!1,places:6},show:!0,type:"esriFieldTypeDouble"})}f&&0<f.length?b.resolve({data:f||[],outFields:d}):a.fromClient?(f=q.map(c.graphics,function(k){return e?B(k):v.clone(k)}),b.resolve({data:f||[],outFields:d})):h._getExportDataFromServer(c,
d,a).then(function(k){b.resolve({data:k||[],outFields:d})});return b};h._getExportDataFromServer=function(c,a,b){var d=new u;if("esri.layers.FeatureLayer"!==c.declaredClass)return d.resolve([]),d;var f=new E(c.url),e=new F;e.where=b.filterExpression||c.getDefinitionExpression&&c.getDefinitionExpression()||"1\x3d1";0<a.length?(c=q.map(a,function(g){return g.name}),e.outFields=c):e.outFields=["*"];e.returnGeometry=b.withGeometry;f.execute(e,function(g){g=q.map(g.features,function(k){return B(k)});d.resolve(g)},
function(g){console.error(g);d.resolve([])});return d};h._formattedData=function(c,a,b){var d=new u,f=[],e=a.data;a=a.outFields;for(var g=t.getFeatureLayerDefinition(c),k=0,l=e.length;k<l;k++){for(var n={},r=0;r<a.length;r++){var p=a[r];n[p.alias||p.name]=h._getExportValue(e[k][p.name],p,c.objectIdField,c.typeIdField,e[k][c.typeIdField],c.types,b,g,e[k],c)}f.push(n)}c=q.map(a,function(m){return m.alias||m.name});d.resolve({datas:f,columns:c,appendColumns:b.appendColumns,appendDatas:b.appendDatas});
return d};h._getExportValue=function(c,a,b,d,f,e,g,k,l,n){function r(y){if(p&&D.isDefined(p.fieldInfos))for(var z=0,G=p.fieldInfos.length;z<G;z++){var C=p.fieldInfos[z];if(C.fieldName===y)return C.format}return null}var p=g.popupInfo,m=!!a.domain&&g.formatCodedValue;g="esriFieldTypeDate"===a.type&&g.formatDate;var x=b&&a.name===b;d=d&&a.name===d;n=n&&n.renderer?n:k;return g?t.fieldFormatter.getFormattedDate(c,r(a.name)):(d||m)&&k&&l&&(k=t.getDisplayValueForCodedValueOrSubtype(n,a.name,l))&&k.hasOwnProperty("displayValue")?
k.displayValue:m||g||x||d?c:(m=null,b&&e&&0<e.length&&(b=(b=q.filter(e,function(y){return y.id===f}))&&b[0])&&b.domains&&b.domains[a.name]&&b.domains[a.name].codedValues&&(a=t.getDisplayValueForCodedValueOrSubtype(n,a.name,l))&&a.hasOwnProperty("displayValue")&&(m=a.displayValue),null!==m?m:c)}});