import { Modifier, Placement } from '@popperjs/core';
export * from './flip';
/**
 * A Popper.js modifier to change the size of your popper to fit it within the available viewport space.
 */
export declare const maxSizeModifier: Modifier<any, any>;
/**
 * A Popper.js modifier to apply the style generated by maxSizeModifier
 */
export declare const applyMaxSizeModifier: Modifier<any, any>;
/**
 * A Popper.js modifier to set the standby placements
 * @param fallbackPlacements
 * @param flipPlacement Whether to flip placement during RTL
 */
export declare const getFallbackPlacementsModifier: (fallbackPlacements: Placement[], flipPlacement?: boolean) => Partial<Modifier<any, any>>;
