// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-construct dijit/_TemplatedMixin dijit/_WidgetBase".split(" "),function(k,g,h,f,l,m){return k([m,l],{name:"SEFilterEditor",baseClass:"jimu-widget-sefilterEditor",declaredClass:"jimu.dijit.SEFilterEditor",templateString:"\x3cdiv style\x3d'width:100%'\x3e\x3cdiv data-dojo-attach-point\x3d'filterEditorDiv'\x3e\x3c/div\x3e\x3c/div\x3e",_templatePicker:null,_layers:null,map:null,nls:null,_origGetItemsFromLayerFunc:null,postCreate:function(){this._createFilterTool()},
_createFilterTool:function(){this._createLayerFilter();this._createTemplateFilter();this._loadTemplates()},_createLayerFilter:function(){this.selectDropDown=f.create("select",{"class":"flDropDown templatePicker",tabindex:"0","aria-label":this.nls.filterEditor.filterLayerLabel});f.place(this.selectDropDown,this.filterEditorDiv);this.selectDropDown.onchange=g.hitch(this,function(){this._onLayerFilterChanged()})},removeOptions:function(a){var b;for(b=a.options.length-1;0<=b;b--)a.remove(b)},_loadTemplates:function(){var a=
this.selectDropDown.value===this.nls.filterEditor.all||""===this.selectDropDown.value?null:this.selectDropDown.value,b=this.filterTextBox.value,d=!1;this.removeOptions(this.selectDropDown);var e=f.create("option",{value:this.nls.filterEditor.all,innerHTML:this.nls.filterEditor.all});f.place(e,this.selectDropDown);for(e=0;e<this._layers.length;e++){var c=this._layers[e];!0===c.visible&&!0===c.visibleAtMapScale&&(null!==a&&c.id===a&&(d=!0),c=f.create("option",{value:c.id,innerHTML:c.name}),f.place(c,
this.selectDropDown))}!0===d&&(this.selectDropDown.value=a,this._onLayerFilterChanged());null!==b&&""!==b&&(this.filterTextBox.value=b,this._onTemplateFilterChanged())},setTemplatePicker:function(a,b){this._layers=b;this._templatePicker=a;this._overrideTemplatePicker();this._loadTemplates()},_createTemplateFilter:function(){this.filterTextBox=f.create("input",{"class":"searchtextbox templatePicker",type:"text",placeholder:this.nls.filterEditor.searchTemplates},this.filterEditorDiv);this.filterTextBox.onkeyup=
g.hitch(this,function(){this._onTemplateFilterChanged()});this._overrideTemplatePicker()},_overrideTemplatePicker:function(){this._origGetItemsFromLayerFunc=this._templatePicker._getItemsFromLayer;this._templatePicker._getItemsFromLayer=g.hitch(this,function(){var a=this._origGetItemsFromLayerFunc.apply(this._templatePicker,arguments);var b=this.filterTextBox.value;b&&(a=h.filter(a,function(d){var e=!1,c=new RegExp(b,"ig");d.hasOwnProperty("label")&&d.label.match(c)&&0<d.label.match(c).length&&(e=
!0);d.hasOwnProperty("template")&&d.template.hasOwnProperty("name")&&d.template.name.match(c)&&0<d.template.name.match(c).length&&(e=!0);return e}));0===a.length&&(this._templatePicker.grid.noDataMessage=this.nls.filterEditor.noAvailableTempaltes);return a})},_onLayerFilterChanged:function(){this._templatePicker.clearSelection();var a=this.selectDropDown.options[this.selectDropDown.selectedIndex].text;""!==a&&(a===this.nls.filterEditor.all?(a=h.filter(this._layers,function(b){return!0===b.visible&&
!0===b.visibleAtMapScale}),this._templatePicker.attr("featureLayers",a),""===this.filterTextBox.value?this._templatePicker.attr("grouping",!0):this._templatePicker.attr("grouping",!1)):(a=this.map.getLayer(this.selectDropDown.value),this._templatePicker.attr("featureLayers",[a]),this._templatePicker.attr("grouping",!1)),this._templatePicker.update())},_onTemplateFilterChanged:function(){var a=this.filterTextBox.value;this.selectDropDown.options[this.selectDropDown.selectedIndex].text===this.nls.filterEditor.all&&
""===a?this._templatePicker.attr("grouping",!0):this._templatePicker.attr("grouping",!1);this._templatePicker.update()}})});