import { Expression } from 'jimu-core';
export declare const EXTERNAL_ID = "expression-0";
export declare const DATA_SOURCE_ID = "ds1";
export declare const JIMU_FIELD_NAME = "f1";
export declare const twoUnmergeablePartsExp: Expression;
export declare const oneUnmergeablePartAndOneMergeablePart: Expression;
export declare const oneMergeablePartAndOneUnmergeablePart: Expression;
export declare const mergeablePartBetweenTwoUnmergeableParts: Expression;
export declare const unmergeablePartBetweenTwoUnmergeableParts: Expression;
export declare const unmergeablePartBetweenOneUnmergeablePartAndOneMergeablePart: Expression;
export declare const unmergeablePartBetweenOneMergeablePartAndOneUnmergeablePart: Expression;
export declare const unmergeablePartBetweenTwoMergeableParts: Expression;
export declare const oneStringPartBetweenTwoUnmergeableParts: Expression;
export declare const oneStringPartBetweenOneUnmergeablePartAndOneMergeablePart: Expression;
export declare const oneStringPartBetweenOneMergeablePartAndOneUnmergeablePart: Expression;
export declare const oneStringPartBetweenTwoMergeableParts: Expression;
export declare const oneFieldPartBetweenTwoUnmergeableParts: Expression;
export declare const oneFieldPartBetweenOneUnmergeablePartAndOneMergeablePart: Expression;
export declare const oneFieldPartBetweenOneMergeablePartAndOneUnmergeablePart: Expression;
export declare const oneFieldPartBetweenTwoMergeableParts: Expression;
