// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("exports dojo/_base/lang dojo/_base/array dojo/_base/html dojo/_base/kernel dojo/has dojo/number dojo/Deferred jimu/utils esri/lang esri/tasks/QueryTask esri/tasks/query esri/graphic jimu/ArcadeUtils".split(" "),function(g,r,p,A,D,y,E,w,v,F,G,H,I,J){function B(c){var a=r.clone(c.attributes);(c=c.geometry)&&"point"===c.type&&("x"in a?a._x=c.x:a.x=c.x,"y"in a?a._y=c.y:a.y=c.y);return a}g.exportCSV=function(c,a,b){return g._createCSVStr(a,b).then(function(d){return g._download(c+".csv",d)})};
g.exportCSVFromFeatureLayer=function(c,a,b){b=b||{};return g._getExportData(a,{datas:b.datas,objectIds:b.objectIds,fromClient:b.fromClient,withGeometry:b.withGeometry,outFields:b.outFields,filterExpression:b.filterExpression,outSpatialReference:b.outSpatialReference,arcadeExpressions:b.arcadeExpressions,geometry:b.geometry,orderByFields:b.orderByFields,start:b.start,num:b.num}).then(function(d){return g._formattedData(a,d,{formatNumber:b.formatNumber,formatDate:b.formatDate,formatCodedValue:b.formatCodedValue,
richText:{clearFormat:b.richTextFieldsToClear&&!!b.richTextFieldsToClear.length,fieldsToClear:b.richTextFieldsToClear||[]},popupInfo:b.popupInfo}).then(function(k){return g.exportCSV(c,k.datas,k.columns)})})};g.exportCSVByAttributes=function(c,a,b,d){d=r.mixin({},d);d.datas=b;return g.exportCSVFromFeatureLayer(c,a,d)};g.exportCSVByGraphics=function(c,a,b,d){b=p.map(b,function(k){return k.attributes});return g.exportCSVByAttributes(c,a,b,d)};g._createCSVStr=function(c,a){var b=new w,d="",k=0,e=0,f=
"",l="",m=","===E.format(1.1,{locale:D.locale}).substring(1,2)?";":",";try{a=p.map(a,function(n){return"string"===typeof n?{name:n}:n});p.forEach(a,function(n){n=n.alias||n.name;-1<n.toString().indexOf(m)&&(n='"'+n+'"');d=d+f+n;f=m});d+="\r\n";k=c.length;e=a.length;for(var h=0;h<k;h++){f="";for(var q=0;q<e;q++){(l=c[h][a[q].name])||"number"===typeof l||(l="");if("string"===typeof l){var t=!1;(t=";"===m?/[";\r\n]/g.test(l):/[",\r\n]/g.test(l))&&(l='"'+l.replace(/(")/g,'""')+'"')}d=d+f+l;f=m}d+="\r\n"}b.resolve(d)}catch(n){console.error(n),
b.resolve("")}return b};g._isIE11=function(){return 11===v.has("ie")};g._isEdge=function(){return v.has("edge")};g._getDownloadUrl=function(c){return window.Blob&&window.URL&&window.URL.createObjectURL?(c=new Blob(["\ufeff"+c],{type:"text/csv"}),URL.createObjectURL(c)):"data:attachment/csv;charset\x3dutf-8,\ufeff"+encodeURIComponent(c)};g._download=function(c,a){var b=new w;try{if(y("ie")&&10>y("ie")){var d=window.top.open("about:blank","_blank");d.document.write("sep\x3d,\r\n"+a);d.document.close();
d.document.execCommand("SaveAs",!0,c);d.close()}else if(10===y("ie")||g._isIE11()||g._isEdge()){var k=new Blob(["\ufeff"+a],{type:"text/csv"});navigator.msSaveBlob(k,c)}else{var e=A.create("a",{href:g._getDownloadUrl(a),target:"_blank",download:c},document.body);if(y("safari")){var f=document.createEvent("MouseEvents");f.initEvent("click",!0,!0);e.dispatchEvent(f)}else e.click();A.destroy(e)}b.resolve()}catch(l){b.reject(l)}return b};g._getExportData=function(c,a){var b=new w,d=null,k=[],e=a.datas,
f=a.withGeometry,l=!!a.arcadeExpressions;d=a.outFields;d&&d.length||(d=c.fields);d=r.clone(d);if(f&&!(e&&0<e.length)){l?(k=p.filter(c.fields,function(h){return-1===h.name.indexOf("expression/")}),k=r.clone(k)):k=r.clone(d);var m="";m=-1!==d.indexOf("x")?"_x":"x";d.push({name:m,alias:m,format:{digitSeparator:!1,places:6},show:!0,type:"esriFieldTypeDouble"});m=-1!==d.indexOf("y")?"_y":"y";d.push({name:m,alias:m,format:{digitSeparator:!1,places:6},show:!0,type:"esriFieldTypeDouble"})}e&&0<e.length?(l&&
(e=g._getAttrsWithExpressionsBatch(e,a.arcadeExpressions)),b.resolve({data:e||[],outFields:d})):a.fromClient?(e=p.map(c.graphics,function(h){h=f?B(h):r.clone(h);return h=l?g._getAttrsWithExpressions(h,a.arcadeExpressions):h}),b.resolve({data:e||[],outFields:d})):g._getExportDataFromServer(c,k,a).then(function(h){l&&(h=g._getAttrsWithExpressionsBatch(h,a.arcadeExpressions));b.resolve({data:h||[],outFields:d})});return b};g._getExportDataFromServer=function(c,a,b){var d=new w;if("esri.layers.FeatureLayer"!==
c.declaredClass)return d.resolve([]),d;var k=new G(c.url),e=new H;e.where=b.filterExpression||c.getDefinitionExpression&&c.getDefinitionExpression()||"1\x3d1";0<a.length?(c=p.map(a,function(f){return f.name}),e.outFields=c):e.outFields=["*"];e.objectIds=b.objectIds;e.returnGeometry=b.withGeometry;e.outSR=b.spatialReference;e.geometry=b.geometry;e.orderByFields=b.orderByFields;e.start=b.start;e.num=b.num;e.outSpatialReference=b.outSpatialReference;k.execute(e,function(f){f=p.map(f.features,function(l){return B(l)});
d.resolve(f)},function(f){console.error(f);d.resolve([])});return d};g._formattedData=function(c,a,b){var d=new w,k=[],e=a.data;a=a.outFields;for(var f=0,l=e.length;f<l;f++){for(var m={},h=0;h<a.length;h++){var q=a[h];m[q.name]=g._getExportValue(e[f][q.name],q,c.objectIdField,c.typeIdField,e[f][c.typeIdField],c.types,b)}k.push(m)}c=p.map(a,function(t){return{alias:t.alias,name:t.name}});d.resolve({datas:k,columns:c});return d};g._getExportValue=function(c,a,b,d,k,e,f){function l(x){if(h&&F.isDefined(h.fieldInfos))for(var u=
0,z=h.fieldInfos.length;u<z;u++){var C=h.fieldInfos[u];if(C.fieldName===x)return C.format}return null}function m(x){for(var u=0,z=q.length;u<z;u++)if(q[u].fieldName===x)return!0;return!1}var h=f.popupInfo,q=f.richText.fieldsToClear,t=!!a.domain&&f.formatCodedValue,n="esriFieldTypeDate"===a.type&&f.formatDate,K=b&&a.name===b;d=d&&a.name===d;m="esriFieldTypeString"===a.type&&f.richText.clearFormat&&m(a.name);return n?v.fieldFormatter.getFormattedDate(c,l(a.name)):d?v.fieldFormatter.getTypeName(c,e):
t?v.fieldFormatter.getCodedValue(a.domain,c):m?c?(a=document.createElement("span"),a.innerHTML=c,a.textContent||a.innerText||""):c:t||n||K||d||m?c:(f=null,b&&e&&0<e.length&&(b=(b=p.filter(e,function(x){return x.id===k}))&&b[0])&&b.domains&&b.domains[a.name]&&b.domains[a.name].codedValues&&(f=v.fieldFormatter.getCodedValue(b.domains[a.name],c)),null!==f?f:c)};g._getAttrsWithExpressions=function(c,a){var b=r.getObject("expressionInfos",!1,a);a=r.getObject("layerDefinition",!1,a);var d=new I(null,null,
c);return J.customExpr.getAttributesFromCustomArcadeExpr(b,d,a)||c};g._getAttrsWithExpressionsBatch=function(c,a){var b=[];return b=p.map(c,function(d){return g._getAttrsWithExpressions(d,a)})}});