// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/lang dojo/_base/array dojo/aspect dojo/Deferred dojo/cookie dojo/json dojo/topic dojo/request/script esri/kernel esri/config esri/request esri/urlUtils esri/sniff esri/IdentityManager esri/arcgis/OAuthInfo jimu/portalUrlUtils jimu/utils esri/layers/vectorTiles/kernel".split(" "),function(e,l,B,v,p,C,w,x,f,r,D,E,G,y,H,h,F,I){"function"!==typeof p.getAll&&(p.getAll=function(a){var b=[];(a=p(a))&&b.push(a);return b});y={portalUrl:null,cookiePath:"/",_started:!1,webTierPortalUrls:[],
isInBuilderWindow:function(){return!!window.isBuilder},isInConfigOrPreviewWindow:function(){return F.isInConfigOrPreviewWindow()},isStringStartWith:function(a,b){return a.substr(0,b.length)===b},getCookiePath:function(){return this.cookiePath},setPortalUrl:function(a){(a=h.getStandardPortalUrl(a))&&(a+="/");this.portalUrl=a},getPortalUrl:function(){return this.portalUrl},isWebTierPortal:function(a){var b=new v,c=h.getStandardPortalUrl(a);a=c+"/sharing";var d=h.setHttpsProtocol(c+"/sharing/generateToken?f\x3djson"),
g=h.setHttpsProtocol(a);x.get(d,{jsonp:"callback"}).then(e.hitch(this,function(k){k.token?(this.webTierPortalUrls.push(c),this.removeWabAuthCookie(),f.id.getCredential(g).then(e.hitch(this,function(m){function t(n){var z=n.creationTime||(new Date).getTime(),A=n.expires;0<z&&0<A&&A>z&&setTimeout(function(){x.get(d,{jsonp:"callback"}).then(function(q){q.token&&(n.token=q.token,n.expires=q.expires,n.creationTime=(new Date).getTime(),n.refreshServerTokens(),t(n))},function(q){console.error(q)})},.8*(A-
z))}m.token||(m.token=k.token);m.expires||(m.expires=k.expires);var u=this.findServerFromCorsEnabledServers(m.server);-1<u&&r.defaults.io.corsEnabledServers.splice(u,1);this._pushCorsEnabledServerInfo({host:h.getServerByUrl(c),withCredentials:!0});b.resolve(!0);t(m)}),e.hitch(this,function(){b.resolve(!0)}))):b.resolve(!1)}),e.hitch(this,function(k){console.error(k);b.reject(k)}));return b},addAuthorizedCrossOriginDomains:function(a){if(a&&0<a.length)for(var b=0;b<a.length;b++)this.addWithCredentialDomain(a[b])},
addWithCredentialDomain:function(a){if(a&&"string"===typeof a){var b=r.defaults.io.corsEnabledServers,c=h.getServerByUrl(a);(a=h.getServerWithProtocol(a))||(a="http://"+c);a=this.findServerFromCorsEnabledServers(a);-1<a&&b.splice(a,1);this._pushCorsEnabledServerInfo({host:c,withCredentials:!0})}},findServerFromCorsEnabledServers:function(a){var b=r.defaults.io.corsEnabledServers,c,d=-1;G("esri-cors")&&b&&b.length&&l.some(b,function(g,k){g=!g||"object"!==typeof g||g instanceof RegExp?g:g.host;return!(g instanceof
RegExp)&&g&&(c=0!==g.trim().toLowerCase().indexOf("http"),E.hasSameOrigin(a,c?"http://"+g:g)||c&&E.hasSameOrigin(a,"https://"+g))?(d=k,!0):!1});return d},_pushCorsEnabledServerInfo:function(a){if(a){var b=r.defaults.io.corsEnabledServers,c="charAt charCodeAt concat endsWith indexOf lastIndexOf localeCompare match replace search slice split startsWith substr substring toLocaleLowerCase toLocaleUpperCase toLowerCase toString toUpperCase trim trimLeft trimRight valueOf".split(" ");if("object"===typeof a&&
"string"===typeof a.host){for(var d in a.host)a[d]="function"===typeof a.host[d]?function(){return a.host[d].apply(a.host,arguments)}:a.host[d];a.length=a.host.length;l.forEach(c,function(g){"function"===typeof a.host[g]&&(a[g]=function(){return a.host[g].apply(a.host,arguments)})})}b.push(a)}},tryRegisterCredential:function(a){return this.isValidCredential(a)?l.some(f.id.credentials,e.hitch(this,function(b){return a.token===b.token}))?!1:(f.id.credentials.push(a),!0):!1},registerToken:function(a){var b=
h.getSharingUrl(this.portalUrl);f.id.findCredential(b)&&l.some(f.id.credentials,e.hitch(this,function(c,d){if(this.isValidPortalCredentialOfPortalUrl(this.portalUrl,c))return f.id.credentials.splice(d,1),!0}));return this._getTokenInfo(a).then(function(c){c&&f.id.registerToken(c)})},_getTokenInfo:function(a){var b=h.getPortalSelfInfoUrl(this.portalUrl);return x.get(b+("?f\x3djson\x26token\x3d"+a),{jsonp:"callback"}).then(e.hitch(this,function(c){return c.user?{server:h.getSharingUrl(this.portalUrl),
ssl:c.allSSL,token:a,userId:c.user.username}:null}),function(c){console.error(c);throw Error(window.jimuNls.urlParams.validateTokenError);})},_isInvalidPortalUrl:function(a){return a&&"string"===typeof a&&e.trim(a)},signInPortal:function(a){var b=new v;if(this._isInvalidPortalUrl(a)){a=h.getStandardPortalUrl(a);var c=h.getSharingUrl(a),d=this.getPortalCredential(a);d?setTimeout(e.hitch(this,function(){b.resolve(d)}),0):b=f.id.getCredential(c)}else setTimeout(e.hitch(this,function(){b.reject("Invalid portalurl.")}),
0);return b},_loadPortalSelfInfo:function(a){a=h.getPortalSelfInfoUrl(a);return D({url:a,handleAs:"json",content:{f:"json"},callbackParamName:"callback"})},registerOAuthInfo:function(a,b){if(!a||"string"!==typeof a||!b||"string"!==typeof b)return null;var c=f.id.findOAuthInfo(a);c||(c=window.location.protocol+"//"+window.location.host+require.toUrl("jimu")+"/oauth-callback.html",c=new H({appId:b,expiration:20159,portalUrl:a,authNamespace:"/",popup:!0,popupCallbackUrl:c}),f.id.registerOAuthInfos([c]));
c.appId=b;return c},signOutAll:function(){var a=h.getStandardPortalUrl(this.portalUrl),b=!!f.id.findCredential(a+"/sharing/rest");window.appInfo.isRunInPortal?this.removeEsriAuthCookieStorage():this.removeWabAuthCookie();f.id.destroyCredentials();f.id._oAuthHash=null;b&&this._publishCurrentPortalUserSignOut(a)},userHaveSignInPortal:function(a){return!!this.getPortalCredential(e.trim(a||""))},isValidCredential:function(a){var b=!1;if(a){b=a.token;var c=a.server,d=a.scope;b=b&&"string"===typeof b&&
e.trim(b);c=c&&"string"===typeof c&&e.trim(c);d="portal"===d||"server"===d;var g=!0;a.expires&&(a=parseInt(a.expires,10),g=(new Date).getTime(),g=a>g);b=b&&c&&d&&g}return b},isValidPortalCredentialOfPortalUrl:function(a,b){var c=!1;this.isValidCredential(b)&&(c="portal"===b.scope,a=h.isSameServer(a,b.server),c=c&&a);return c},getPortalCredential:function(a){var b=null;a=e.trim(a||"");if(!a)return null;a=h.getStandardPortalUrl(a);(b=this._filterPortalCredential(a,f.id.credentials))||this._tryConvertArcGIScomCrendentialToOrgCredential();
return b},_tryConvertArcGIScomCrendentialToOrgCredential:function(){var a=this.portalUrl;if(a&&(a=h.getStandardPortalUrl(a),h.isOrgOnline(a)&&!this._filterPortalCredential(a,f.id.credentials))){var b=this._filterPortalCredential("http://www.arcgis.com",f.id.credentials);b&&f.id.registerToken({token:b.token,scope:"portal",userId:b.userId,server:a+"/sharing/rest",expires:b.expires})}},saveAndRegisterCookieToCredential:function(a){a=e.clone(a);a.referer=window.location.host;a.scope="portal";a.isAdmin=
!!a.isAdmin;this.saveWabCookie(a);var b=a.server+"/sharing/rest";a.server=b;f.id.registerToken(a);return f.id.findCredential(b,a.userId)},registerAuth2Hash:function(a){a=e.clone(a);var b=1E3*parseInt(a.expires_in,10);b=(new Date).getTime()+b;var c=h.getStandardPortalUrl(a.state.portalUrl);return this.saveAndRegisterCookieToCredential({referer:window.location.host,server:c,token:a.access_token,expires:b,userId:a.username,scope:"portal",isAdmin:!!a.isAdmin})},saveWabCookie:function(a){this.removeCookie("wab_auth");
p("wab_auth",C.stringify(a),{expires:new Date(a.expires),path:"/"})},removeWabAuthCookie:function(){this.removeCookie("wab_auth")},removeEsriAuthCookieStorage:function(){this.removeCookie("esri_auth");window.localStorage&&window.localStorage.removeItem("esriJSAPIOAuth");window.sessionStorage&&window.sessionStorage.removeItem("esriJSAPIOAuth")},_filterPortalCredential:function(a,b){var c=null;a=h.getStandardPortalUrl(a);b&&0<b.length&&(b=l.filter(b,e.hitch(this,function(d){return this.isValidPortalCredentialOfPortalUrl(a,
d)})),0<b.length&&(c=b[b.length-1]));return c},_removePortalCredential:function(a){var b=e.trim(a||"");if(b){b=h.getStandardPortalUrl(b);for(a=l.filter(f.id.credentials,e.hitch(this,function(c){return this.isValidPortalCredentialOfPortalUrl(b,c)}));0<a.length;)a[0].destroy(),a.splice(0,1);f.id.credentials=l.filter(f.id.credentials,e.hitch(this,function(c){return!this.isValidPortalCredentialOfPortalUrl(b,c)}))}},getUserIdByToken:function(a,b){var c=new v;if(a&&"string"===typeof a&&b&&"string"===typeof b){var d=
h.getStandardPortalUrl(b);b=l.filter(f.id.credentials,e.hitch(this,function(k){var m=k.token===a&&k.userId;k=h.isSameServer(d,k.server);return m&&k}));if(0<b.length){var g=b[0];setTimeout(e.hitch(this,function(){c.resolve(g.userId)}),0);return c}b=h.getCommunitySelfUrl(d);D({url:b,handleAs:"json",content:{f:"json"},callbackParamName:"callback"}).then(e.hitch(this,function(k){c.resolve(k&&k.username||"")}),e.hitch(this,function(k){console.error(k);c.reject("fail to get userId by token")}))}else setTimeout(e.hitch(this,
function(){c.reject("invalid parameters")}),0);return c},xtGetCredentialFromCookie:function(a){var b=p("wab_auth"),c=null;if(b)try{c=C.parse(b)}catch(d){console.error(d)}if(!c||"object"!==typeof c||!h.isSameServer(a,c.server)||window.location.host!==c.referer)return null;c.expires=parseInt(c.expires,10);b=(new Date).getTime();if(!(c.expires>b))return this.removeCookie("wab_auth"),null;a+="/sharing/rest";c.server=a;(b=f.id.findCredential(a))||f.id.registerToken(c);return b=f.id.findCredential(a)},
removeCookie:function(a){var b=this.getCookiePath();F.removeCookie(a,b)},_getDomainsByServerName:function(a){var b=a.split("."),c=b.length;return l.map(b,e.hitch(this,function(d,g){d=b.slice(g,c);var k="",m=d.length-1;l.forEach(d,e.hitch(this,function(t,u){k+=t;u!==m&&(k+=".")}));return k}))},_publishCurrentPortalUserSignIn:function(a){if(this.isValidCredential(a))try{w.publish("userSignIn",a)}catch(b){console.error(b)}},_publishAnyUserSignIn:function(a){if(this.isValidCredential(a))try{w.publish("anyUserSignIn",
a)}catch(b){console.error(b)}},_publishCurrentPortalUserSignOut:function(a){try{w.publish("userSignOut",a)}catch(b){console.error(b)}},_signInSuccess:function(a){try{this.isValidPortalCredentialOfPortalUrl(this.portalUrl,a)&&this._publishCurrentPortalUserSignIn(a),this._publishAnyUserSignIn(a)}catch(b){console.error(b)}},_bindEvents:function(){B.after(f.id,"signIn",e.hitch(this,function(a,b){console.log(b[1]);B.after(a,"callback",e.hitch(this,function(c,d){this._signInSuccess(d[0],!1)}));return a}))},
isStart:function(){return this._started},startup:function(){if(!this._started){if(this.isInConfigOrPreviewWindow()){var a=window.parent;if(a){var b=a.esri&&a.esri.id;b._wab="builder";if(b){f.id=b;var c=window.esriConfig.defaults.io;a=a.esriConfig.defaults.io;c.corsEnabledServers=a.corsEnabledServers;c.webTierAuthServers=a.webTierAuthServers;c._processedCorsServers=a._processedCorsServers;c.corsStatus=a.corsStatus;Object.defineProperty(I,"id",{get:function(){return b},enumerable:!0,configurable:!0})}}}this._bindEvents();
this._started=!0}}};y.startup();return y});